# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.4
_src_path: https://github.com/jupyterlab/extension-template
advanced: false
author_email: jupyter@googlegroups.com
author_name: Project Jupyter
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: '@jupyter-ai-contrib/live-content'
project_short_description: A minimal JupyterLab extension that provides live content
    updates from the filesystem.
python_name: jupyter_live_content
repository: https://github.com/jupyter-ai-contrib/jupyterlab-live-content
test: true

